#+title: Emacs init.el Literate Configuration
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/init.el
+ Para exportar utilize ~C-c C-v t~
  
* Index Of
  - [[Core]]
    - [[Configuração Editor]]
      - [[Inicializar arquivos]]
      - [[Backup]]
      - [[Ambiente UTF]]
      - [[Manter pacotes recentes]]
      - [[Uteis nativos]]
      - [[Melpa]]
      - [[Org-Agenda]]
      - [[Org-Mode]]
      - [[Tema Emacs]]
    - [[Funções Elisp]]
      - [[Criar LaTeX]]
      - [[Binds Emacs]]
      - [[ERC]]
    - [[Pacotes]]
      - [[Slack-C]]
      - [[Org-Modern]]
      - [[Projectile]]
      - [[Dashboard]]
      - [[Evil-Mode]]
      - [[VTerm]]
      - [[Vertico]]
      - [[Orderless]]
      - [[Savehist]]
      - [[Org-Roam]]
      - [[Which-Key]]
      - [[Marginalia]]
  - [[Extensão]]
    - [[Linguagens]]
      - [[Treesiter]] 
    - [[Checker & LSP]]
      - [[Flycheck]]
      - [[Flycheck Popup]]
	
* Core
** Configuração Editor
*** Inicializar arquivos
Aqui estou iniciando um arquivo de configuração de ambiente do Emacs.
#+begin_src emacs-lisp
  ;;; init.el --- Configurações do meu Emacs -*- lexical-binding: t; -*-
  ;; Inicializar o arquivo usado para configurações do ambiente  
  (load-file (expand-file-name "ambiente.el" user-emacs-directory))
#+end_src

*** Backup
Definir o diretório de arquivos backups do Emacs. Preferi manter do que desativar, para casos raros de travamento ou quedas de luz.
#+begin_src emacs-lisp
  (setq backup-directory-alist                                             ;; Definir o diretório de backups
        `(("." . ,(expand-file-name "backups/" user-emacs-directory))))    ;; Procurar backups/ dentro do diretório do Emacs
#+end_src

*** Ambiente UTF
#+begin_src emacs-lisp
  (prefer-coding-system 'utf-8-unix)             ;; Definindo UTF Unix
  (set-language-environment "UTF-8")             ;; ^
  (set-face-attribute 'default nil :height 140)  ;; Tamanho da fonte
#+end_src

*** Manter pacotes recentes
#+begin_src emacs-lisp
  (setq load-prefer-newer t                      ;; Mantém os .el mais recentes
        inhibit-startup-message t)
#+end_src

*** Uteis nativos
Se quiser novamente os menus do Emacs, apenas altere para =1=.
#+begin_src emacs-lisp
  (global-display-line-numbers-mode 1)           ;; Exibir o número da linha
  (scroll-bar-mode -1)                           ;; Desliga a scrollbar do Emacs (ON 1 | -1 OFF)
  (menu-bar-mode -1)                             ;; Desliga os menus do Emacs
  (tool-bar-mode -1)                             ;; Desligar o menu de ferramentas
#+end_src

*** Melpa
Descomente a linha sempre que for instalar pela primeira vez.
#+begin_src emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
;;(package-refresh-contents)
#+end_src

*** Org-Agenda
As configurações da agenda nativa do Emacs.
O arquivo =tasks.org= é para os headers Org da agenda onde as tarefas são salvas.
#+begin_src emacs-lisp
  (use-package org-habit)                        ;; Ligar os hábitos
  (use-package org-agenda
  :custom
  (org-agenda-files '("tasks.org"))
  (org-agenda-start-with-log-mode t))
#+end_src

*** Org-Mode
#+begin_src emacs-lisp
  (use-package org
    :ensure t
    :custom
    (org-directory (file-truename ambiente/org-workflow))    ;; Diretório de trabalho do Org
    (org-habit-show-habits t)                                ;; Exibir os hábitos na agenda
    (org-startup-truncated t)                                ;; Deixar arquivos ORG truncados

    ;; Binds para os TODO para usar na Agenda
    (org-todo-keywords '((sequence "TODO(t)" "ONGOING(o)" "WAIT(w@)" "|" "DONE(d!)" "CANCELED(c@)")
  		       (sequence "[ ](T)" "[-](O)" "[?](W)" "|" "[X](D)")
  		       (sequence "POST(p)" "|" "POSTED(P!)")
  		       (sequence "TOREAD(r)" "|" "READ(R!)")
  		       (sequence "TOLEARN(l)" "|" "LEARNED(L!)")))

    ;; Modelos de capturas para notas
    (org-capture-templates '(
  			   ;;; Tarefas pessoais
  			   ("t" "Tarefas")
  			   ("tg" "Geral" entry (file+olp ambiente/org-workflow-tasks "Geral")
  			    "* TODO %? :task: \nSCHEDULED: %^t\n%i" :empy-lines-after 1)
  			   ;;; Tarefas de hábitos
  			   ("r" "Rotina" entry (file+olp ambiente/org-workflow-tasks "Rotinas")
  			    "* TODO %? :habt: \nSCHEDULED: %^t.+1d\n:PROPERTIES:\n:STYLE:    habit\n:END:\n%i" :empty-lines-after 1)
  			   ))
    
    :bind 
    ("C-c a" . org-agenda)
    ("C-c l" . org-store-link)
    ("C-c c" . org-capture) )
#+end_src

*** Tema Emacs
#+begin_src emacs-lisp
  ;;(load-theme 'modus-vivendi t)
  ;;(load-theme 'tsdh-dark t)
  (load-theme 'wombat t)
#+end_src

** Funções Elisp
*** Fechar blocos
#+begin_src emacs-lisp
  (when (fboundp 'electric-pair-mode)            ;; Fechar blocos () {}
    (electric-pair-mode t))                      
#+end_src

*** Criar LaTeX
Essa é uma função minha que criei para criar arquivos como se fosse o Org-Roam.
#+begin_src emacs-lisp
  (use-package emacs
    :preface
    (defun open-new-latex-file ()
      "Abrir um novo arquivo Latex dentro do roam."
      (interactive)
      (let* ((directory-name "~/Documents/org/roam/latex/")
  	   (file-name (read-from-minibuffer "Filename: ")))
        (with-temp-file (format "%s/%s.tex" directory-name file-name))
        (find-file (format "%s/%s.tex" directory-name file-name))
      ))
    :bind ("C-c x" . open-new-latex-file))
#+end_src

*** Binds Emacs
Aqui é uma gambiarra minha que serve para abrir o arquivo de configuração do Emacs.
#+begin_src emacs-lisp
  (use-package emacs                           
  :config
  (defun open-init-file-config ()
    "Abrir arquivo de configuração."
    (interactive)
    (find-file ambiente/emacs-config))
  :bind ("C-x c" . open-init-file-config))       ;; Abrir o arquivo Org de configuração
#+end_src

Uma gambiarra para definir uma keybind para ~restart-emacs~.
#+begin_src emacs-lisp
(global-set-key (kbd "C-c r") #'restart-emacs)
#+end_src

*** ERC
O ~ERC~ é um cliente do protocolo IRC. Aqui é a configuração do servidor padrão que será usado.
#+begin_src emacs-lisp
  (setq erc-server ambiente/irc-ip)              ;; Endereço do servidor
  (setq erc-port ambiente/irc-porta)             ;; Porta do servidor
#+end_src

** Pacotes
*** Slack-C
Meu pacote criado para criar projetos em C pré-configurados por template.
#+begin_src emacs-lisp
  (use-package slack-c 
    ;;:ensure nil
    :vc (:url "https://github.com/rahvax/slack-c.el.git"
  	    :rev :newest)
    :custom
    (slackc-dir-path "~/Documents/Forgejo/"))
#+end_src

*** Org-Modern
Esse pacote está sendo encontrado apenas usado com ~package-vc-install~, por algum motivo que ainda não sei.
#+begin_src emacs-lisp
  (use-package org-modern
    :after org
    :config
    (global-org-modern-mode))
#+end_src

*** Projectile
O Projectile é um gerenciador de projetos do Emacs, que é usado aqui de forma integrada no [[Dashboard]] e com o [[Magit]].
#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :init
    (projectile-mode)
    :bind-keymap
    ("C-c p" . projectile-command-map))
#+end_src

*** Dashboard
#+begin_src emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (setq dashboard-banner-logo-title ambiente/emacs-welcome)                                  ;; Banner usado
    (setq dashboard-startup-banner ambiente/emacs-banner)                                      ;; ^
    (setq dashboard-center-content t)                                                          ;; Centralizar os conteúdos
    (setq dashboard-items '((projects  . 5)                                                    ;; Exibir a ordem e quantia de conteúdos
                            (recents   . 2)
                            (agenda    . 5)))
    (setq dashboard-vertically-center-content t)                                               ;; Centralizar as categorias
    (setq dashboard-display-icons-p t)                                                          
    (setq dashboard-icon-type 'all-the-icons)                                                  ;; Usar o All-The-Icons como fonte de ícones
    (dashboard-modify-heading-icons '((recents   . "file-text")                                ;; Os emojis usados para a categoria
                                     (projects . "file-directory") (agenda . "database")))
    (setq dashboard-set-heading-icons t)                                                       ;; Exibir emoji de categoria
    (setq dashboard-set-file-icons t)                                                          ;; Exibir os ícones dos arquivos
    (setq dashboard-projects-switch-function 'projectile-switch-project-by-name)               ;; Usar a função switch do Projectile ao dar <ENTER>
    (setq dashboard-projects-backend 'projectile)                                              ;; Usar o Projectile
    (dashboard-setup-startup-hook)                                                             ;; Chamar o Dashboard como inicial
  )
  ;; Habilitar os pacotes usados de fontes de emojis
  (use-package nerd-icons
    :ensure t)
  (use-package all-the-icons :ensure t)
#+end_src

*** Editorconfig
Permitir as configurações personalizadas por projeto e global, para o editor. Configurações essas como tamanho do tab por blocos.
#+begin_src emacs-lisp
  (use-package editorconfig
    :ensure t
    :config
    (editorconfig-mode 1))
#+end_src

*** Evil-Mode
Usar os atalhos e modos do editor VIM. Para desabilitar em um arquivo é só usar =C-z=.
#+begin_src emacs-lisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-keybinding nil)
    :config
    (evil-mode 1))
  (use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))
#+end_src

*** VTerm
Um terminal para o Emacs. 
#+begin_src emacs-lisp
  (use-package vterm
    :ensure t
    :init
    (defun run-vterm-custom ()
      "This function will run vterm inside the project root or in the current directory."
      (interactive)
      (if (projectile-project-p) (projectile-run-vterm) (vterm default-directory)))

    (defun run-vterm-other-window-custom ()
      "This function will run vterm in other window inside the project root or in the current directory."
      (interactive)
      (if (projectile-project-p) (projectile-run-vterm-other-window) (vterm-other-window default-directory)))
    
    :bind (("C-c t" . run-vterm-custom)
  	 ("C-c C-t" . run-vterm-other-window-custom)))
#+end_src

*** Vertico
Exibir as informações do =M-x=.
#+begin_src emacs-lisp
  (use-package vertico
  :ensure t
  :init
  (vertico-mode)
  :custom
  (vertico-cycle t)
)
#+end_src

*** Orderless
Melhorar as informações exibidas no =M-x= com o [[Vertico]].
  #+begin_src emacs-lisp
 (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion))))
    :config
    (defun just-one-face (fn &rest args)
      (let ((orderless-match-faces [completions-common-part]))
        (apply fn args)))

    (advice-add 'company-capf--candidates :around #'just-one-face)
    (setq orderless-component-separator "[ &]"))
#+end_src

*** Savehist
Salvar os usos anteriores do =M-x=.
#+begin_src emacs-lisp
  (use-package savehist
    :ensure t
    :init
    (savehist-mode))
#+end_src

*** Magit
O gerenciador GIT do Emacs. É muito útil para trabalhar em repositórios de forma bem mais flexível.
#+begin_src emacs-lisp
  (use-package magit
    :ensure t)
#+end_src

*** Org-Roam
Uma forma mais organizada de gerenciar e vincular as anotações em Org-Mode.
#+begin_src emacs-lisp
  (use-package org-roam
    :ensure t
    :custom
    (org-roam-directory (file-truename ambiente/org-workflow-roam))     ;; Diretório workflow do Roam
    :bind (
  	 ("C-c n f" . org-roam-node-find)                             ;; Pesquisar anotações | ou criar abaixo \/
  	 ("C-c n c" . org-roam-capture)                               ;; Criar uma nova captura por template
  	 )
    :config
    ;;; É o layout na hora de criar notas
    (setq org-roam-node-display-template
  	(concat "${title:*} "
  		(propertize "${tags:10}" 'face 'org-tag)))
    (org-roam-db-autosync-enable)                                       ;; Ligar a sincronização SQLITE
    (require 'org-roam-protocol)                                        ;; Protocolo usado para exportar notas como Org-Roam-UI
    ;;; Modelos de capturas que serão usados
    (setq org-roam-capture-templates '(
  				     ("t" "Tecnologia")
  				     ("tf" "Ferramentas" plain "%?"
  				      :target (file+head "tech/tools/${slug}.org"                                             ;; head permite colocar um cabeçalho
  							 "#+title: Tools: ${title}\n#+date: %U\n#+filetags: :tools:\n\n")     ;; Eis o cabeçalho
  				      :unarrowed t)
  				     ("tr" "Redes" plain "%?"
  				      :target (file+head "tech/net/$(slug).org"
  							 "#+title: Network: $(title)\n#+date: %U\n#+filetags: :network:\n\n")
  				      :unarrowed t)
  				     ("tg" "Gerais" plain (file "~/Documents/org/templates/tech.org")
  				      :target (file "tech/$(slug).org")
  				      :unarrowed t)

  				     ("g" "Geral" plain (file "~/Documents/org/templates/notas.org")                           ;; Usando um template em arquivo
  				      :target (file "${slug}.org")                                                             ;; Arquivo a ser criado
  				      :unarrowed t)                                                                            ;; Exibir tudo no buffer de captura

  				     ))
    )
#+end_src

*** Which-Key
Uma forma boa de lembrar as binds do Emacs. Ao apertar alguma combinação, após uns segundos, ele vai exibir as possibilidades de binds que possuí.
#+begin_src emacs-lisp
  (use-package which-key
  :ensure t
  :hook (after-init . which-key-mode)
  :config
  (which-key-setup-side-window-bottom))
#+end_src

*** Marginalia
Exibir comentários úteis dentro do =M-x= para as funções encontradas.
#+begin_src emacs-lisp
  (use-package marginalia
    :ensure t
    :after (vertico)    ;; Garantir que o Vertico venha primeiro
    :init
    (marginalia-mode)
    :config
    (add-to-list
     'marginalia-annotators
     '(marginalia-annotators-heavy marginalia-annotators-light nil)))
#+end_src

* Extensão
** Linguagens
*** Treesiter
Definindo a lista de repositórios para download.
#+begin_src emacs-lisp
  (setq treesit-language-source-alist
  	      '(
  		(c "https://github.com/tree-sitter/tree-sitter-c")
  		(make "https://github.com/alemuller/tree-sitter-make")
  		(markdown "https://github.com/ikatyang/tree-sitter-markdown")
  		(python "https://github.com/tree-sitter/tree-sitter-python")
  		(toml "https://github.com/tree-sitter/tree-sitter-toml")
  		(yaml "https://github.com/ikatyang/tree-sitter-yaml")
  		(cpp "https://github.com/tree-sitter/tree-sitter-cpp")
  		(cmake "https://github.com/uyha/tree-sitter-cmake")
  		))
#+end_src
** Checker & LSP
*** Flycheck
Um checker para syntax. Isso já resume praticamente.
#+begin_src emacs-lisp
  (use-package flycheck
    :ensure t
    :init                      ;; Hooks para antes do pacote ser carregado
    (global-flycheck-mode))    ;; Ativar o flycheck globalmente
#+end_src

*** Flycheck Popup
Exibir um pop-up dos avisos do Flycheck. Ele usa o ~popup.el~, diferente do ~posframe.el~ do ~Flycheck-posframe~. É mais básico para meu uso.
#+begin_src emacs-lisp
  (use-package flycheck-popup-tip
    :ensure t
    :after flycheck
    :hook (flycheck-mode . flycheck-popup-tip-mode))
#+end_src
*** Eglot
